project_id = "bwimmqwtmrprnrhdszts"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false